version: '3.8'

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn_server
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    sysctls:
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    volumes:
      - openvpn_storage_loop:/etc/openvpn
    restart: always
    # The '|' character ensures literal line breaks are preserved!
    command: |
      sh -c "
      if [ ! -f /etc/openvpn/ovpn_env.sh ]; then
        echo 'Detecting VPS Public IP Address...';
        PUBLIC_IP=$$(wget -qO- https://api.ipify.org);
        echo 'Detected IP:' $$PUBLIC_IP;
        
        echo 'Initializing OpenVPN configuration...';
        ovpn_genconfig -u udp://$$PUBLIC_IP:1194;
        
        echo 'Generating PKI keys (This takes a few minutes)...';
        export EASYRSA_BATCH=1;
        export EASYRSA_REQ_CN=OpenVPN-Dokploy;
        ovpn_initpki nopass;
      fi;
      
      if [ ! -f /etc/openvpn/pki/issued/dokploy-client.crt ]; then
        echo 'Generating Dokploy Client Profile...';
        easyrsa build-client-full dokploy-client nopass > /dev/null 2>&1;
        
        echo 'client' > /etc/openvpn/dokploy-client.ovpn;
        echo 'disable-dco' >> /etc/openvpn/dokploy-client.ovpn;
        echo 'pull-filter ignore \"block-outside-dns\"' >> /etc/openvpn/dokploy-client.ovpn;
        echo 'redirect-gateway def1' >> /etc/openvpn/dokploy-client.ovpn;
        echo 'mssfix 1300' >> /etc/openvpn/dokploy-client.ovpn;
        
        ovpn_getclient dokploy-client | grep -v '^client' >> /etc/openvpn/dokploy-client.ovpn;
      fi;
      
      for i in 1 2 3 4 5; do
        echo '';
        echo '===================================================================';
        echo \"                 YOUR READY-TO-USE .OVPN PROFILE (PRINT $$i OF 5)  \";
        echo '          Copy everything below this box into a text file          ';
        echo '===================================================================';
        cat /etc/openvpn/dokploy-client.ovpn;
        echo '===================================================================';
        echo '';
        sleep 1;
      done;
      
      echo 'Starting OpenVPN Server...';
      ovpn_run
      "

volumes:
  openvpn_storage_loop: